### ISSUE TITLE
Version out of date with Beaker Browser

### ISSUE THREAD

**Issue by jondashkyle** [beakerbrowser/bkr#15]
When attempting to use the newest version of Beaker (0.6.1) with the bkr CLI, an error appears stating:

> Bkr version is 1.1.0 and minimum required is 2.0.0. Please update bkr!

**Comment by pfrazee** [comment]
Did you try updating bkr?

**Comment by pfrazee** [comment]
`npm i -g bkr`

**Comment by pfrazee** [comment]
Oh Im a jerk. I didnt publish

**Comment by pfrazee** [comment]
Sorry about that. Try now.

**Comment by jondashkyle** [comment]
;)

Thanks!
