### ISSUE TITLE
Has bkr implemented the .dat sparse mode option?

### ISSUE THREAD

**Issue by PiviSys** [beakerbrowser/bkr#17]

**Comment by pfrazee** [comment]
There's an open PR right now to fix sparse mode -- we're waiting on @mafintosh to merge. https://github.com/mafintosh/hyperdrive/pull/128.

What command did you encounter this with?

**Comment by PiviSys** [comment]
bkr publish. It seems when trying to request specific files from a dat, the request seems to work fine and quickly on a lan connection, but when requesting over a wan link the file will only download a small chunk. No consistency in the size of the small chunk.
