### ISSUE TITLE
Nice to have: clearer P2P workflow example?

### ISSUE THREAD

**Issue by miguelpaz** [beakerbrowser/bkr#19]
As a distributed P2P system in a browser, that allows to share information and files in a distributed network with others that use Beaker, using encryption, and with CLI, clone, fork, etc. capabilities, I think (for non coders) it would be nice to have clearer P2P workflow examples. Ok I got my secret url and I want to share it with you. How do I do it?  I am still figuring out how this sharing of url's happen and but I can see this used in specific domains of Journalism. I wonder if it also supports emojis like :metal:

**Comment by pfrazee** [comment]
Hey Miguel, sorry for the delay

This particular repo is for `bkr`, the commandline tool that's mainly for programmers. The main repo is https://github.com/beakerbrowser/beaker.

We're working on Beaker 0.7 right now, which is focused on some first workflows. We have all users create a first website in a setup flow. We add tools for quickly sharing files, sharing text documents (like a pastebin), creating new sites, and editing a site. It should be fairly simple - each of these actions get you P2P URLs which you share with other Beaker users, and then they can open just like any website.

So -- usability, help, and workflows are our focus now
