### ISSUE TITLE
Supported beaker version

### ISSUE THREAD

**Issue by millette** [beakerbrowser/bkr#20]
I'm giving bkr a try, using bkr 2.0.2 and beaker browser 0.7.2.

Launched beaker browser, created a new directory and tried ```bkr init``` only to get the error
> Error: Could not connect to Beaker. Is it running?

Am I missing something, or is it just a question of incompatible versions?

**Comment by pfrazee** [comment]
Oh gosh, sorry, I thought we updated this repo. We deprecated bkr. We improved how Beaker works with the OS (using the [staging area](https://beakerbrowser.com/docs/using-beaker/staging-area.html)) and we felt like it'd be better to simplify by removing bkr.

I'll update the readme for this. If you think we screwed up by deprecating bkr, feel free to say so!

**Comment by millette** [comment]
I will have to investigate further. I really like my command line :-)

In this case, I'm using a static site generator (gatsby) and wanted to publish it thru dat/beaker. If you have any hints for that, it would be appreciated.

**Comment by pfrazee** [comment]
Yeah, take a look at https://beakerbrowser.com/docs/tutorials/create-a-blog.html. You'll just need to create a site in beaker, and then change the folder to your gatsby output folder

> I really like my command line :-)

Me too

**Comment by millette** [comment]
It's alive! It's alive!

bkr could probably still be useful in an npm script, maybe... I'd be willing to help maintaining it if it's judged necessary to bring brk back.

**Comment by pfrazee** [comment]
:D
