### ISSUE TITLE
Minor—bkr dev on totally empty directory fails

### ISSUE THREAD

**Issue by fasiha** [beakerbrowser/bkr#5]
Operation System: macOS 
bkr version: 1.1.0 (per npm)

Attempted to follow [screencast](https://beakerbrowser.com/docs/howto/use-bkr.html) with an empty directory: `mkdir testing && cd testing && bkr dev` produces:
```
➜  testing bkr dev

  Building '/.../bkr-stuff/testing'...
fs.js:885
  binding.lstat(pathModule._makeLong(path), req);
          ^

TypeError: path must be a string or Buffer
    at Object.fs.lstat (fs.js:885:11)
    at kick (/usr/local/lib/node_modules/bkr/node_modules/folder-walker/index.js:33:8)
    at /usr/local/lib/node_modules/bkr/node_modules/folder-walker/index.js:44:28
    at FSReqWrap.oncomplete (fs.js:112:15)
```
But if I `touch foo && bkr dev`, all is well.

Sorry to make my first issue be so pedestrian. Much 💕 for bkr.

**Comment by pfrazee** [comment]
> Sorry to make my first issue be so pedestrian.

Not at all, this is a great usability issue. Thanks for the report!

**Comment by pfrazee** [comment]
Ok, re-run `npm install` and make sure you get `folder-walker@2.1.2` and this bug should be fixed. Reopen if you have any more issues.

**Comment by fasiha** [comment]
Do you mean, clone this repo and `npm install` in it? (Because, I don’t see a new bkr version pushed to npmjs.com?) Assuming so, I still seem to get `folder-walker@3.0.0`:
```
$ npm ls folder-walker
bkr@1.1.0 /Users/f/Downloads/bkr
└─┬ dat-node@0.1.3
  └── folder-walker@3.0.0
```

**Comment by pfrazee** [comment]
Oh, folder-walker's releases have gotten confused. Try again; 3.0.1 is now published.

> Do you mean, clone this repo and npm install in it?

I *believe* you can just run an install of bkr again, and its deps will update even if the package itself hasn't (due to the package.json version ranges). If that fails, let me know.
